// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPIdemo.Data;

namespace WebAPIdemo.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    partial class StudentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPIdemo.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Class = "KTPM3",
                            Name = "Tuan Hai"
                        },
                        new
                        {
                            ID = 2,
                            Class = "KTPM1",
                            Name = "Tuan Chung"
                        },
                        new
                        {
                            ID = 3,
                            Class = "KTPM2",
                            Name = "Tuan Anh"
                        },
                        new
                        {
                            ID = 4,
                            Class = "KTPM3",
                            Name = "Tuan Tung"
                        },
                        new
                        {
                            ID = 5,
                            Class = "KTPM1",
                            Name = "Tuan Tu"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
